### ISSUE TITLE
Unable to deploy Solana smart Contract coded in Anchor

### ISSUE THREAD

**Issue by mshoaib112215** [solana-playground/solana-playground#192]
![image](https://github.com/solana-playground/solana-playground/assets/75632120/e313d695-c8ac-4f7b-b44f-5afe4b2b679e)

Hello there!

I need help related to the deployment, I deployed my contract Yesterday (29/01/2024) evening but this always shows me this line when I try to deploy my contract even when I want to deploy the hello_anchor simple contract, it shows me this as shown in image.

If anyone helps me, it would be appreciated, and it would make my day :)

**Comment by acheroncrypto** [comment]
Hey, same as https://github.com/solana-playground/solana-playground/issues/193#issuecomment-1917913749.

Deploying programs require making transactions but devnet doesn't accept transactions currently. It should be fixed soon.

**Comment by kaiqiangh** [comment]
> Hey, same as [#193 (comment)](https://github.com/solana-playground/solana-playground/issues/193#issuecomment-1917913749).
> 
> Deploying programs require making transactions but devnet doesn't accept transactions currently. It should be fixed soon.

Hi,

I am still facing the similar issue that is unable to deploy program on devnet.

<img width="1378" alt="image" src="https://github.com/solana-playground/solana-playground/assets/9014062/36a70ded-231e-45c4-880d-017607e5817a">

**Comment by acheroncrypto** [comment]
Can you share browser console logs(F12)?

**Comment by kaiqiangh** [comment]
Here is the screenshot. The error message is "Transaction simulation failed: This account may not be used to pay transaction fees", but my address on devnet has enough SOL balance.

<img width="1429" alt="image" src="https://github.com/solana-playground/solana-playground/assets/9014062/8a581831-f501-4b86-bac6-4bb8ab7823b3">

**Comment by kaiqiangh** [comment]
yeah, you are right. My address is not owned by the System program. Is it possible to change the ownership? I do not find any solution for that. Thanks

**Comment by acheroncrypto** [comment]
It should be possible to recover from this by creating a transaction to send funds from that wallet but paying the fee from another wallet. You can create another wallet account and use them in a TS file with `pg.wallets`.

Also, I'm curious to know how you changed the owner of your wallet account.

**Comment by kaiqiangh** [comment]
> It should be possible to recover from this by creating a transaction to send funds from that wallet but paying the fee from another wallet. You can create another wallet account and use them in a TS file with `pg.wallets`.
> 
> Also, I'm curious to know how you changed the owner of your wallet account.

I forgot what I did to cause this issue. I would try the way you mentioned. Thanks a million.

**Comment by Aviksaikat** [comment]
> It should be possible to recover from this by creating a transaction to send funds from that wallet but paying the fee from another wallet. You can create another wallet account and use them in a TS file with `pg.wallets`.
> 
> Also, I'm curious to know how you changed the owner of your wallet account.

I'm facing the same issue and my account is also not by system program. I was just using `solana-keygen new` to generate the account so no idea what went wrong
